### ISSUE TITLE
캡슐화 오류

### ISSUE THREAD

**Issue by jisungbin** [GSMYunsung/StudyAndroid#1]
https://github.com/GSMYunsung/StudyAndroid/blob/cb92ba64379bb44dd924a2534b04c79ba677ca29/app/src/main/java/com/example/udemy/viewModel/viewModelChallange/ViewModelChallangeViewModel.kt#L9-L15

안드로이드 공부 하시는거 같은데, 도움좀 드리자면 위 코드에서 캡슐화가 잘못되었습니다.

캡슐화 관련 내용은 https://programmar.tistory.com/42 여기를 참고해 보세요.

올바른 캡슐화를 위해 코드가
```kotlin
private val _value = MutableLiveData<String>() 
 val value: LiveData<String> // 변경됨
     get() = _value 
  
 private val _num = MutableLiveData<String>() 
 val num: LiveData<String> // 변경됨
     get() = _num 
```

로 수정되어야 합니다.

공부 하시는데 간단한 도움 드리고 싶은 목적으로 이슈 쓴거니, 기분 나쁘게 훈수처럼 생각하지 말아주세요 :)

**Comment by GSMYunsung** [comment]
앗! 성빈님 감사합니다!  생각해보니 기존 변수에 MutableLiveData 를 쓴다면 프레그먼트나 엑티비티에서 접근해 값을 바꿀 수 도 있겠네요!
그렇게 된다면 캡슐화를 쓰는 의미가 없어질거 같습니다! 피드백 감사하고 빠른 시일내에 고치도록하겠습니다
앞으로 정확한 캡슐화를 사용하도록 하겠습니다. 😆
